version: '3'

services:
  redis:
    image: redis:alpine
    restart: always

  front:
    image: ghcr.io/mailu/front:2024.06
    restart: always
    env_file: mailu.env
    ports:
      - "25:25"
      - "465:465"
      - "993:993"
      - "995:995"
      - "4190:4190"
    volumes:
      - ./certs:/certs
      - ./overrides:/overrides
    depends_on:
      - redis

  admin:
    image: ghcr.io/mailu/admin:2024.06
    restart: always
    env_file: mailu.env
    volumes:
      - ./data:/data
    depends_on:
      - redis

  webmail:
    image: ghcr.io/mailu/roundcube:2024.06
    restart: always
    env_file: mailu.env
    depends_on:
      - front

  antispam:
    image: ghcr.io/mailu/rspamd:2024.06
    restart: always
    env_file: mailu.env
    depends_on:
      - front

volumes:
  certs:
  overrides:
  data: 