version: '3.8'

services:
  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mosala-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - mosala-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`projetmosala.org`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  # Backend NestJS
  backend:
    build:
      context: ./mosala-api
      dockerfile: Dockerfile
    container_name: mosala-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/mosala
      - PORT=4002
    ports:
      - "4002:4002"
    depends_on:
      - db
    networks:
      - mosala-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.projetmosala.org`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=4002"

  # Base de données MySQL
  db:
    image: mysql:8.0
    container_name: mosala-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mosala
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mosala-network

  # Traefik reverse proxy
  traefik:
    image: traefik:v2.10
    container_name: mosala-traefik
    restart: unless-stopped
    ports:
      - "9000:80"
      - "9443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/data
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@projetmosala.org"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    networks:
      - mosala-network

volumes:
  mysql_data:
  traefik_data:

networks:
  mosala-network:
    driver: bridge
