version: '3.8'

services:
  frontend:
    image: nginx:alpine
    container_name: mosala-frontend
    restart: unless-stopped
    ports:
      - "1199:80"
    volumes:
      - ./frontend-temp:/usr/share/nginx/html
    networks:
      - mosala-net

  backend-nestjs:
    image: node:18-alpine
    container_name: mosala-backend-nestjs
    restart: unless-stopped
    working_dir: /app
    command: sh -c "echo 'Backend NestJS en cours de construction...' && tail -f /dev/null"
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=development
    networks:
      - mosala-net

  db:
    image: mysql:8.0
    container_name: mosala-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mosala
      MYSQL_USER: mosala
      MYSQL_PASSWORD: mosala
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3326:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mosala-net
    command: --default-authentication-plugin=mysql_native_password

  postgres:
    image: postgres:15
    container_name: mosala-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mosala
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mosala-net

volumes:
  db_data:
  pg_data:

networks:
  mosala-net:
    driver: bridge
