#!/bin/bash

# Test des tables Supabase
# Affiche les informations sur les tables existantes

echo "==================================="
echo "VÉRIFICATION DES TABLES SUPABASE"
echo "==================================="
echo ""
echo "Les tables suivantes doivent exister en Supabase:"
echo ""
echo "✅ users"
echo "   - id (SERIAL PRIMARY KEY)"
echo "   - name (VARCHAR)"
echo "   - email (VARCHAR UNIQUE)"
echo "   - role (user_role ENUM: 'admin', 'admin_content', 'superadmin')"
echo "   - is_active (BOOLEAN)"
echo "   - created_at, updated_at (TIMESTAMP)"
echo ""
echo "✅ news"
echo "   - id (SERIAL PRIMARY KEY)"
echo "   - title (VARCHAR)"
echo "   - description (TEXT)"
echo "   - content (TEXT)"
echo "   - is_featured (BOOLEAN)"
echo "   - is_published (BOOLEAN)"
echo "   - author_id (INTEGER, FK users)"
echo "   - created_at, updated_at (TIMESTAMP)"
echo ""
echo "✅ formations_advanced"
echo "   - id (SERIAL PRIMARY KEY)"
echo "   - title (VARCHAR)"
echo "   - description (TEXT)"
echo "   - content (TEXT)"
echo "   - level (formation_level ENUM)"
echo "   - status (formation_status ENUM)"
echo "   - duration (INTEGER)"
echo "   - author_id (INTEGER, FK users)"
echo "   - created_at, updated_at (TIMESTAMP)"
echo ""
echo "==================================="
echo ""
echo "Pour créer ces tables:"
echo "1. Allez sur https://app.supabase.com"
echo "2. Cliquez sur SQL Editor"
echo "3. Copiez le contenu de SUPABASE_MIGRATION.sql"
echo "4. Collez et exécutez"
echo ""
echo "==================================="
