name: Déploiement automatique sur VPS

on:
  workflow_dispatch:

jobs:
  deploy-on-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest code and redeploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /opt/mosala-job-hub
            git pull origin main
            docker compose down
            docker compose up --build -d
